sudo: required

services:
  - docker

env:
  - IMAGE="openjdk:7" IPR=5
  - IMAGE="openjdk:8" IPR=5

before_install:
  - docker -v

install:
  - make BUILDARGS="--build-arg IMAGE=$IMAGE --build-arg IPR=$IPR"
