sudo: required

services:
  - docker

env:
  - IMAGE="openjdk:7"
  - IMAGE="openjdk:8"

before_install:
  - docker -v

install:
  - (cd core && make BUILDARGS="--build-arg IMAGE=$IMAGE)
  - (cd data && make)